# Generated by Django 5.1 on 2024-08-25 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('juzgado', models.TextField(max_length=50)),
                ('TipoDeTramite_origen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tramites.tipodetramite')),
            ],
        ),
    ]
